### PR TITLE
feat: add Docker container build script

### PR DESCRIPTION
**Pull request by tomsaleeba**
I've added a build script to make a Docker container. I haven't actually done the challenges yet so I'm not 100% if it's got everything that's needed (and the right versions) but if/when I get a chance to do them, I'll confirm that. I thought I'd send the PR now though so others can get some use.

I've added instructions on how to build in the README but if you auto build the docker container on Docker cloud, you can just get people to pull the image from the main registry rather than building locally.

I decided to have the Docker build call `make` so it's all ready to go. This means the src/ isn't there, so no cheating. But it means your message at the end of `make` probably won't be seen. I was thinking of doing a `make | tee make.log` in the docker build and maybe even doing a `cat` of the log when you run the Docker image so you see the message on startup.

### CODE REVIEW

**Comment by disconnect3d** [comment]
Hey,

Thanks for the PR!

This is a great idea to add a docker image for that.

I will review this, check if everything works fine and add it later to docker registry hub.

**Comment by disconnect3d** [comment]
Hey,

Thanks for the PR!

> NOTE: This should REALLY be a Docker container. If you mind to create one, simply create a Pull Request! ;)

If we ever meet in real life, ping me to get a free beer :beer:

I will review this, check if everything works fine and add it later to docker registry hub.

**Comment by tomsaleeba** [comment]
Very happy to help out.

**Comment by disconnect3d** [comment]
Oh sry, I missed this for so long. I will just assume it works fine, so I am merging this. Thx! ;)

**Comment by tomsaleeba** [comment]
Hey, not a problem. I've only just got around to trying the challenges. I'm up to number 4 and so far it seems I've got the tools I need. If it turns out there's more needed, I'll send another PR.

**Pull request merged**
